### PR TITLE
added gray out action (Issue #52)

### PR DESCRIPTION
**Pull request by VladOstrovski**
So, If you'll run this code you'll see that not all the document is grayed out. This is because I can't seem to find a combination of my Highlighter layer and the Rainbow highlighter severity to run before the rainbow highlighter but after everything else. Maybe you'll have any ideas?

### CODE REVIEW

**Comment by VladOstrovski** [comment]
@izhangzhihao My code is an Action, so it runs whenever an action event occurs. (In this case when the user press "ctrl + alt + /".
So my highlighter has to run from there. Not when the IDE starts... 
Try running the plugin and pressing "ctrl + alt + /" and you'll see what I mean.

**Comment by izhangzhihao** [comment]
I don't think that I totally get your idea, what do you mean of
> find a combination of my Highlighter layer and the Rainbow highlighter severity to run before the rainbow highlighter but after everything else

**Comment by VladOstrovski** [comment]
@izhangzhihao Let me explain better.
As soon as I press ctrl + alt + /, my action code is called (`ToggleGrayOutAction.kt`). Inside my action code I add a `RangeHighlighter`, to color the whole text other than the brackets in an appropriate color.
One of the configurations of this `RangeHighlighter` is what is the highlighter's layer. I have many options there but no matter what I choose i get one of the following results:
image
Which is almost the desired result (brackets are not highlighter, but not all text is highlighted).

Or:
image
Which is a bit less desired (everything highlights including brackets).

I also tried changing the `HighlightSeverity.INFORMATION` in `RainbowHighlighter` to try to change the order of highlighting, but this didn't help.

So, my question is do you have any idea how i can solve this? or maybe the whole `RangeHighlighter` is not the way to go at all?

**Comment by YiiGuxing** [comment]
branch [scope-highlighting](https://github.com/izhangzhihao/intellij-rainbow-brackets/tree/scope-highlighting) has already implemented this function

**Comment by VladOstrovski** [comment]
Not exactly what i had in mind.. but i guess we can close this PR..

**Pull request closed without merging**
