### PR TITLE
Add language exclusions to settings (closes #1046)

### LINKED ISSUE #1046: Option to configure file types to apply rainbow to
It'd be nice if we had an option to configure which file types (probably by file extension) get rainbow applied.  For example, maybe I want JavaScript rainbowified, but not Java.  I've seen it pop up warnings on big files saying it won't rainbowify it, but I don't need it to process that file anyway (e.g. SQL).  So in addition to being able to choose the behavior you want, it could save some processing too.

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by keeganwitt** [comment]
I know we need a screenshot added to README.

I also was having the Kotlin plugin throwing a Throwable with no message and also something about a memory leak in it locally when running `gradle buildPlugin`, so I'm not sure if I've missed something.

**Comment by keeganwitt** [comment]
I'm also not sure if we want to have some kind of backwards compatibility for people that have manually configured this in the file.

**Comment by izhangzhihao** [comment]
> I know we need a screenshot added to README.
> 
> I also was having the Kotlin plugin throwing a Throwable with no message and also something about a memory leak in it locally when running `gradle buildPlugin`, so I'm not sure if I've missed something.

That's a bug of the Kotlin plugin itself, https://youtrack.jetbrains.com/issue/KTIJ-145

**Comment by izhangzhihao** [comment]
> I'm also not sure if we want to have some kind of backwards compatibility for people that have manually configured this in the file.

So, why not just keep using `languageBlacklist`?

**Comment by keeganwitt** [comment]
> 
> 
> > I'm also not sure if we want to have some kind of backwards compatibility for people that have manually configured this in the file.
> 
> So, why not just keep using `RainbowSettings.languageBlacklist`?

Well I think this is way easier to use by having it exposed in settings.  What do you think about combining anything they may have in the file with whatever they have in settings for backwards compatibility?

**Comment by izhangzhihao** [comment]
I guess we could just rename `languagesToExclude` to `languageBlacklist` .

**Comment by keeganwitt** [comment]
I see. I thought those settings were separate from the UI settings. I think I mis-understod how the persistence worked.

**Review by izhangzhihao — APPROVED** [review]

**Comment by izhangzhihao** [comment]
LGTM, merged.

**Pull request merged**
